
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Evandro Teruel
 */
public class TelaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaUsuario
     */
    public TelaUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCargo = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        cmbCargo = new javax.swing.JComboBox<>();

        setTitle("Controle de usuários");
        getContentPane().setLayout(null);

        lblUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 51, 153));
        lblUsuario.setText("Usuário");
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(30, 40, 110, 40);

        txtUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(153, 0, 51));
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(140, 40, 300, 40);

        lblSenha.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(0, 51, 153));
        lblSenha.setText("Senha");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(30, 100, 110, 40);

        txtSenha.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtSenha.setForeground(new java.awt.Color(153, 0, 51));
        getContentPane().add(txtSenha);
        txtSenha.setBounds(140, 100, 300, 40);

        lblNome.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 51, 153));
        lblNome.setText("Nome");
        getContentPane().add(lblNome);
        lblNome.setBounds(30, 160, 110, 40);

        txtNome.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtNome.setForeground(new java.awt.Color(153, 0, 51));
        getContentPane().add(txtNome);
        txtNome.setBounds(140, 160, 490, 40);

        lblCargo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblCargo.setForeground(new java.awt.Color(0, 51, 153));
        lblCargo.setText("Cargo");
        getContentPane().add(lblCargo);
        lblCargo.setBounds(30, 220, 110, 40);

        btnSalvar.setBackground(new java.awt.Color(51, 102, 153));
        btnSalvar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(30, 280, 140, 40);

        cmbCargo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmbCargo.setForeground(new java.awt.Color(153, 0, 51));
        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Analista", "Estagiário", "Gerente", "Professor", "Programador", "Vendedor" }));
        getContentPane().add(cmbCargo);
        cmbCargo.setBounds(140, 220, 280, 40);

        setSize(new java.awt.Dimension(733, 390));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //1 - Obter os dados que foram digitados nos campos.
        String u, s, n, c;
        u = txtUsuario.getText();
        s = txtSenha.getText();
        n = txtNome.getText();
        c = cmbCargo.getSelectedItem().toString();
        //2 - Verificar se o usuário e senha não estão vazios (nulos).
        if (u.isEmpty()) {
            JOptionPane.showMessageDialog(null, "A digitação do usuário é obrigatória");
            txtUsuario.requestFocus();
            return; //stop
        }
        if (s.isEmpty()) {
            JOptionPane.showMessageDialog(null, "A digitação da senha é obrigatória");
            txtSenha.requestFocus();
            return; //stop
        }
        try {
            //3.1 Conectar com o banco de dados.     
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conecta = DriverManager.getConnection("jdbc:mysql://localhost:3307/bdsistema", "root", "admin");
            //3.2 Enviar os dados (salvar) para a tabela usuarios do banco de dados.
            PreparedStatement st = conecta.prepareStatement("INSERT INTO usuarios VALUES(?,?,?,?)");
            st.setString(1, u);
            st.setString(2, s);
            st.setString(3, n);
            st.setString(4, c);
            st.executeUpdate(); //executa o INSERT
            JOptionPane.showMessageDialog(null, "Usuário salvo com sucesso");
            txtUsuario.setText("");
            txtSenha.setText(""); 
            txtNome.setText("");
            cmbCargo.setSelectedIndex(0);
            //3.3 Fechar conexão com o banco de dados (desconectar).
            conecta.close();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
